name: Validate and publish

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    branches:
      - 'main'

jobs:
  validate-and-publish:
    permissions:
      id-token: write
    runs-on: macos-latest
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: 🔎 Show tool versions
        run: |
          flutter --version
          dart --version
          xcodebuild -version
          pod --version

      - name: 📦 Install Dependencies
        run: flutter pub get

      - name: ✨ Check Formatting
        run: dart format --set-exit-if-changed .

      - name: 🕵️ Analyze
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: 🧪 Test
        run: flutter test

      - name: 🍎 Validate iOS example with Swift Package Manager
        run: |
          flutter config --enable-swift-package-manager
          flutter pub get
          flutter build ios --no-codesign --verbose
        working-directory: example

      - name: 🎯 Setup Dart for pub.dev publishing
        if: startsWith(github.ref, 'refs/tags/v')
        uses: dart-lang/setup-dart@v1

      - name: 🚀 Publish
        if: startsWith(github.ref, 'refs/tags/v')
        run: dart pub publish --force
